name: Build React on S3
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_SECRETE_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-southeast-2 build s3://tasobucket
