name: Slack-Notification

on:
  pull_request:
    types: [opened]

jobs:
  Slack-Notification:
    name: Slack-Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack-Notification
        id: slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          MESSAGE="New Pull Request opened: ${PR_TITLE} by ${PR_AUTHOR}\n${PR_URL}"

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"${MESSAGE}\"
          }" $SLACK_WEBHOOK_URL